apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
    - key: infra
      value: reserved
      effect: NoSchedule
  clientTLS:
    clientCA:
      name: ''
    clientCertificatePolicy: ''
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ''
  replicas: 3
  tuningOptions: {}
  unsupportedConfigOverrides: null
