---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-op-appset
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc

  template:
    metadata:
      name: '{{cluster}}-ingress-controller'
    spec:
      destination:
        namespace: openshift-ingress-operator
        server: '{{url}}'
      project: default
      source:
        repoURL: 'https://github.com/r3dact3d/gitops'
        path: common-base/openshift-ingress-operator
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
