---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-op-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            env: infra
  template:
    metadata:
      name: '{{name}}-ingress-controller'
    spec:
      destination:
        namespace: openshift-ingress-operator
        server: '{{server}}'
      project: default
      source:
        repoURL: 'https://github.com/r3dact3d/gitops'
        path: common-base/openshift-ingress-operator
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
